### ISSUE TITLE
threejs binding

### ISSUE THREAD

**Issue by eviltik** [winter-cardinal/winter-cardinal-ui#105]
Hi, 

Congratulation and thank you for sharing. 

do you think winter-cardinal-ui can be used in a threejs scene ? (with the mouse in a first time, webxr controllers in a second time)

I didn't dive into the code yet, for which reason are you using pixijs ?

**Comment by mofnire** [comment]
Hi, 

At first, I haven't event once tried to use this module in Three.js scenes.
But if you want to, I guess you will need some modifications to PixiJS and WinterCardinal UI to share a WebGL context with Three.js at least.

The reason why I chose PixiJS is is it is a "2D" WebGL library while Three.js is a "3D" WebGL library.
What is more, PixiJS is blazingly fast.

**Comment by eviltik** [comment]
Yeah. I started playing with pixijs + threejs with a canvas texture. Everything is fine until I enter immersive mode: no errors but the texture remains stuck in the state it was in when I entered immersive mode.

I'm closing this ticket and perhaps i'll add tricks later.
