### ISSUE TITLE
Drag behavior is weird

### ISSUE THREAD

**Issue by codehz** [winter-cardinal/winter-cardinal-ui#96]
The object will easily fly off the screen when the mouse is released

https://user-images.githubusercontent.com/13158903/126124400-87ed2ef9-66f1-4b05-97a0-7418af12d609.mp4

**Comment by mofnire** [comment]
Thank you for pointing that out!
It seems like the gesture parameters for `DView` and `UtilGestureEasing` need to be adjusted.

https://github.com/winter-cardinal/winter-cardinal-ui/blob/1c9311ed8b884d4ecc6662b341fa1409f2c02672/src/main/typescript/wcardinal/ui/theme/white/d-theme-white-view.ts#L70-L75

https://github.com/winter-cardinal/winter-cardinal-ui/blob/1c9311ed8b884d4ecc6662b341fa1409f2c02672/src/main/typescript/wcardinal/ui/util/util-gesture-easing.ts#L158-L165

**Comment by codehz** [comment]
> May I ask which version of @wcardinal/wcardinal-ui is used in this video?

https://winter-cardinal.github.io/winter-cardinal-ui/sample/white/chart/bar.html
it is the sample page

**Comment by mofnire** [comment]
> > May I ask which version of @wcardinal/wcardinal-ui is used in this video?
> 
> https://winter-cardinal.github.io/winter-cardinal-ui/sample/white/chart/bar.html
> it is the sample page

Thanks for clarifying.

**Comment by codehz** [comment]
Accurate reproduction steps: press the mouse, move quickly within 1 second, and stop immediately (stay for about 1 seconds), release the mouse

**Comment by codehz** [comment]
it seems if the mouse is not move, the `_histories` will not be updated, that's mean "stop moving" event will not be recorded...
idea: Calculate the speed by the time and position of the last pointermove and pointerup event, if they have same position, that's mean user has stopped moving

**Comment by mofnire** [comment]
> it seems if the mouse is not move, the `_histories` will not be updated, that's mean "stop moving" event will not be recorded...
> idea: Calculate the speed by the time and position of the last pointermove and pointerup event, if they have same position, that's mean user has stopped moving

To check if the mouse is actually stopped, the data in `_histories` that are older than 160 milliseconds are ignored. Namely, if the mouse stops for more than 160 milliseconds, no easing animation takes place. Maybe, 160 milliseconds are too long?

https://github.com/winter-cardinal/winter-cardinal-ui/blob/1c9311ed8b884d4ecc6662b341fa1409f2c02672/src/main/typescript/wcardinal/ui/util/util-gesture-easing.ts#L109-L115

**Comment by codehz** [comment]
> To check if the mouse is actually stopped, the data in `_histories` that are older than 160 milliseconds are ignored. Namely, if the mouse stops for more than 160 milliseconds, no easing animation takes place. Maybe, 160 milliseconds are too long?

It doesn't seems working


https://user-images.githubusercontent.com/13158903/126142594-43f389e0-4378-4b04-9a9c-7fe5b1df88fb.mp4

the problem is that if mouse don't moving, no move event will generated...

**Comment by mofnire** [comment]
> > To check if the mouse is actually stopped, the data in `_histories` that are older than 160 milliseconds are ignored. Namely, if the mouse stops for more than 160 milliseconds, no easing animation takes place. Maybe, 160 milliseconds are too long?
> 
> It doesn't seems working

It's wired. It seems working fine for me.
Which browser are you using?

> the problem is that if mouse don't moving, no move event will generated...

When the pointerup event is generated, `UtilGesture` calculates how long the mouse is stopped by using `PointerEvent#timeStamp` .  Therefore, it is supposed to work even if the pointermove event is not fired.

https://github.com/winter-cardinal/winter-cardinal-ui/blob/1c9311ed8b884d4ecc6662b341fa1409f2c02672/src/main/typescript/wcardinal/ui/util/util-gesture.ts#L316-L322

**Comment by codehz** [comment]
> Which browser are you using?

Microsoft Edge & Chrome (version: 91

**Comment by mofnire** [comment]
> > Which browser are you using?
> 
> Microsoft Edge & Chrome (version: 91

Thank you.

**Comment by mofnire** [comment]
I can not reproduce the issue unfortunately. However, I rewrote `UtilGestureEasing` for improving the easing animation in #97. Please reopen if this doesn't solve the issue. I'm going to publish the NPM package soon to reflect this change.
